schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: "8659675496697de204bc49751ca198"
documents: './src/**/*.graphql'
generates:
  src/lib/generatedGraphQLTypes.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unknown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node