[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-nextjs"