export const locations = [
    "Ashland",
    "Austin",
    "Baltimore",
    "Boston",
    "Boulder",
    "Chicago",
    "Cleveland",
    "Denver",
    "Las Vegas",
    "London",
    "Los Angeles",
    "Louisville",
    "Minneapolis / St. Paul",
    "New York City",
    "Ontario",
    "Orlando",
    "Philadelphia",
    "Pittsburgh",
    "Portland, OR",
    "Raleigh",
    "Salt Lake City",
    "San Francisco / Oakland",
    "Sarasota",
    "Seattle",
    "St. Louis",
    "Toronto",
    "Washington DC",
]

export const affiliations = [
    "AEA",
    "AFM",
    "AGMA",
    "AGVA",
    "ASCAP",
    "BMI",
    "CSA",
    "EMC",
    "IATSE",
    "LMDA",
    "Non-union",
    "SAFD",
    "SAG/AFTRA",
    "SDC",
    "USA",
]
