export const locations = [
    "Ashland",
    "Austin",
    "Baltimore",
    "Boston",
    "Boulder",
    "Chicago",
    "Cleveland",
    "Denver",
    "Las Vegas",
    "London",
    "Los Angeles",
    "Louisville",
    "Minneapolis / St. Paul",
    "New York City",
    "Ontario",
    "Orlando",
    "Philadelphia",
    "Pittsburgh",
    "Portland, OR",
    "Raleigh",
    "Salt Lake City",
    "San Francisco / Oakland",
    "Sarasota",
    "Seattle",
    "St. Louis",
    "Toronto",
    "Washington DC",
]

export const affiliations = [
    "AEA",
    "AFM",
    "AGMA",
    "AGVA",
    "ASCAP",
    "BMI",
    "CSA",
    "EMC",
    "IATSE",
    "LMDA",
    "Non-union",
    "SAFD",
    "SAG/AFTRA",
    "SDC",
    "USA",
]

export const mockData = {
    name: 'Frank Test',
    email: 'frank@franknoirot.co',
    discipline: 'Developer',
    vocalRange: 'A2-D6',
    danceExperience: 'Cupid Shuffle',
    mainLocation: 'NYC',
    // locations: [
    //     'Las Vegas',
    //     'New York City',
    // ],
    // affiliations: [
    //     'AEA',
    //     'EMC',
    // ],
    pronouns: 'He / him',
    genderIdentity: 'Cis',
    sexualIdentity: 'queer?',
    raceEthnicity: 'whyte',
    website: 'franknoirot.co',
    resume: 'franknoirot.github.io/resume',
    whyRok: 'I wanna be the very best',
    referral: 'Like no one ever was.',
}
